dwp/attendance-allowance-prototype

views/index.njk
Added frozen tag to past sprints
=> refactor: added frozen tags

app.js, middleware/locale.js, views/sprint-79/add-contact-details.njk, views/sprint-79/attendance-allowance-ineligible.njk, views/sprint-79/best-describe.njk, views/sprint-79/birth-date-ineligible.njk, views/sprint-79/country-outside-uk-duration-ineligible.njk, views/sprint-79/done.njk, views/sprint-79/helping-someone-intro.njk, views/sprint-79/residence-country-ineligible.njk, views/sprint-79/start.njk, views/sprint-79/who-is-applying-ineligible.njk
?locale=NI variants for 10 pages:
- /start
- /who-is-applying-ineligible
- /best-describe
- /helping-someone-intro
- /birth-date-inelgible
- /attendance-allowance-ineligible
- /country-outside-uk-duration-ineligible
- /residence-country-ineligible
- /add-contact-details
- /application-submitted
=> feat: northern ireland variants

views/sprint-79/report-change-in-circumstances.njk
Changed the warning component from Nunjucks to HMTL
=> feat: warning nunjucks to html

controllers/sprint-79/start/before-you-start.js, views/index.njk, views/sprint-79/before-you-start.njk, views/sprint-79/eligibility.njk, views/sprint-79/how-to-claim.njk, views/sprint-79/overview.njk, views/sprint-79/report-change-in-circumstances.njk, views/sprint-79/what-youll-get.njk
- removed external links from GOVUK pages
- Added routing in for GOVUK pages to replace /start
- Added NI routing to go to /before-you-start and skip GOVUK
=> refactor: remove external links for testing

views/index.njk, views/v5-layouts/layout.njk, views/v5-layouts/prototypeLayout.njk
- updated beta to Beta in phase banner
- added service name
- updated layout.njk to use v5-layouts
=> refactor: updated beta and service name

controllers/sprint-80/age-scaling/age-range-check.js, controllers/sprint-80/age-scaling/age-range-under-state-pension.js, controllers/sprint-80/eligibility/who-is-applying.js, controllers/sprint-80/index.js, routes/sprint-80.js, utils/constants.js, views/sprint-80/age-range-check.njk, views/sprint-80/age-range-ineligible.njk, views/sprint-80/age-range-limit.njk, views/sprint-80/age-range-under-state-pension.njk, views/sprint-80/eligibility.njk, views/sprint-80/how-to-claim.njk, views/sprint-80/overview.njk, views/sprint-80/report-change-in-circumstances.njk, views/sprint-80/what-youll-get.njk
- updated how-to-claim with latest content
- updated age scaling journey
- updated age-range-check to radio buttons
- added age-range-under-state-pension page (variant on /birth-date-ineligible)
=> feat: age range scaling and GOVUK

controllers/sprint-80/age-scaling/age-range-check.js, views/index.njk, views/sprint-80/age-range-check.njk
updated routing for 'Start NI' to include age scaling pages
=> feat: age scaling for NI

views/index.njk, views/sprint-80/macros/check-answers-details-section.njk
- removed care home serco date from CYA
=> refactor: update index notes and CYA

controllers/sprint-80/accessibility/accessibility-statement.js, controllers/sprint-80/index.js, routes/sprint-80.js, utils/constants.js, views/index.njk, views/layouts/layout.njk, views/sprint-80/accessibility-statement.njk, views/v5-layouts/layout.njk
- added accessibility statement
- configured routing
- updated index page notes
=> feat: accessibility statement

views/index.njk, views/sprint-81/helping-someone-intro.njk
- updated helping-someone-intro with new content
=> refactor: updated helping someone to apply

views/sprint-81/helping-someone-intro.njk
=> refactor: NI variant

controllers/sprint-81/eligibility/birth-date.js, controllers/sprint-81/eligibility/other-benefits.js, controllers/sprint-81/eligibility/special-rules-declaration.js, controllers/sprint-81/eligibility/who-is-applying.js, controllers/sprint-81/start/helping-someone-intro.js
Updated routing so that birth-date now comes before special-rules-declaration in the user flow
=> feat: updated routing

controllers/sprint-81/eligibility/special-rules-declaration.js, controllers/sprint-81/eligibility/who-is-applying-ineligible.js
Updated conditional routing for who-is-applying-ineligible if user is return to special-rules-declaration or best-describe
=> feat: updated back routing special rules

views/sprint-81/illness-disability-added.njk
- h1 now counts how many conditions added
- added body text to h2
=> refactor: add health conditions limit

controllers/sprint-82/govuk/eligibility.js, controllers/sprint-82/govuk/how-to-claim.js, controllers/sprint-82/govuk/overview.js, controllers/sprint-82/govuk/report-change-in-circumstances.js, controllers/sprint-82/govuk/what-youll-get.js, views/sprint-82/how-to-claim.njk
=> fix: updated routing

views/index.njk
=> refactor: updated index notes

controllers/sprint-82/identity/home-address-international.js, views/index.njk, views/sprint-82/home-address-international.njk, views/sprint-82/macros/check-answers-details-section.njk
- international address fields
=> refactor: update international address fields

views/sprint-82/limit-reached.njk
- added back link to how-to-claim
=> fix: added back link to how-to-claim

controllers/sprint-82/contact-details/alternative-formats.js, views/sprint-82/alternative-formats.njk, views/sprint-82/macros/check-answers-contact-details-section.njk, views/sprint-82/macros/reword-format.njk, views/sprint-82/other-benefits.njk
- reverted radios to checkboxes
- updated error message
- updated content for the no option
- updated CYA
=> refactor: revert alt formats to checkboxes

views/sprint-82/check-answers-full-list.njk
updated back to claim-submission
=> fix: updated CYA full list back routing

views/sprint-82/how-to-claim.njk
=> refactor: updated how to claim scaling information

views/sprint-82/renal-dialysis-where.njk
=> refactor: updating I'm to I receive

views/sprint-82/safe-day-why.njk
Typo: intrustive and intrusive
=> refactor: updated typo

views/sprint-83/home-address-international.njk, views/sprint-83/home-address-manual.njk
- updated h1s
- updated hint text to body text
=> refactor: updated headings and hint to body

views/index.njk, views/sprint-83/404-v2.njk, views/sprint-83/500.njk, views/sprint-83/503.njk, views/sprint-83/macros/assisted-digital-details.njk
- updated 404 - page not found
- added 500 - there is a problem with the service
- added 503 - service unavailable
- amended assisted digital get help macro
=> refactor: updated 404, 500 and 503 pages

views/index.njk, views/sprint-83/503.njk
updated service unavailable page
=> refactor: updated service unavailable

views/sprint-84/attendance-allowance-ineligible.njk
- removed continue to apply if you are renewing
=> refactor: updated renewals content

views/index.njk, views/sprint-84/macros/assisted-digital-details.njk
- removed email details from 'get help with your application' macro
=> refactor: removed email details from get help

views/sprint-85/how-to-claim.njk
- updated with new GDS content ahead of going live
=> refactor: updated with GDS content

views/index.njk, views/sprint-85/how-to-claim.njk
- updated gov links on how-to-claim
=> refactor: index notes

views/index.njk, views/sprint-86/consent.njk, views/sprint-86/evidence.njk
- new consent design
- updated h1 on evidence
=> refactor: new consent design

controllers/sprint-86/consent/consent.js, views/sprint-86/consent.njk
=> refactor: updated consent error message

views/sprint-87/day-difficulties-copy.njk
- Updated washing and bathing
- Updated social activities and hobbies
=> refactor: day difficulties jess updates

views/v5-layouts/template.njk
Updated privacy link with locale NI variant
=> feat: privacy link variant for NI

views/sprint-88/verification-code.njk
- removed verification code input
- updated content
- added inset text
- updated continue button routing
=> feat: new version for verification code entry

views/sprint-88/residence-country-northern-ireland.njk
Updated NI kick-out screen to redirect to nidirect
=> refactor: northern ireland redirect

views/errors/404.njk
=> refactor: 404 welsh translation

views/sprint-89/500.njk
=> refactor: 500 welsh translation

views/index.njk, views/sprint-89/503.njk
Added Welsh content for 503 service unavailable
=> refactor: 503 welsh translation

views/sprint-89/macros/assisted-digital-details.njk
added Northern Ireland numbers
=> refactor: update get help NI numbers

views/sprint-89/500.njk, views/sprint-89/503.njk
Added telephone and textphone numbers for NI to the 500 and 503 error pages
=> refactor: ni changes 500 503

views/sprint-89/404-ni.njk
Version of 404 page for NI users
=> refactor: 404 ni version

controllers/sprint-89/payability/accommodation-address-outside-uk.js, controllers/sprint-89/payability/care-home-address.js, controllers/sprint-89/payability/care-home-funding-who.js, controllers/sprint-89/payability/care-home-funding.js, controllers/sprint-89/payability/care-home-hospital.js, controllers/sprint-89/payability/hospice-address.js, controllers/sprint-89/payability/hospital-address.js, controllers/sprint-89/payability/other-accommodation-address.js
Updated error messages across the care home / hospital journey
=> refactor: updated care home error messages

controllers/sprint-89/payability/accommodation-address-outside-uk.js, controllers/sprint-89/payability/care-home-funding-who.js, controllers/sprint-89/payability/care-home-funding.js, views/sprint-89/care-home-funding-who.njk, views/sprint-89/macros/check-answers-details-section.njk
Updated routing and CYA information for care home or hospital
=> feat: care home hospital CYA

controllers/sprint-89/identity/home-address-international.js, views/sprint-89/home-address-international.njk
=> fix: update optional input fields

views/sprint-86/macros/check-answers-details-section.njk, views/sprint-87/macros/check-answers-details-section.njk, views/sprint-88/macros/check-answers-details-section.njk, views/sprint-89/macros/check-answers-details-section.njk, views/sprint-90/macros/check-answers-details-section.njk
- updated care home CYA
- updated consent CYA
=> refactor: updates to check answers

controllers/sprint-90/eligibility/country-outside-uk-benefits.js, controllers/sprint-90/eligibility/country-outside-uk-duration.js, controllers/sprint-90/eligibility/country-outside-uk-working.js, controllers/sprint-90/identity/national-insurance.js, controllers/sprint-90/index.js, routes/sprint-90.js, utils/constants.js, views/index.njk, views/sprint-90/country-outside-uk-benefits.njk, views/sprint-90/country-outside-uk-working.njk, views/sprint-90/macros/check-answers-details-section.njk, views/v5-layouts/template.njk
- added /country-outside-uk-benefits
- added /country-outside-uk-working
- updated routing files
- updated footer to match DWP external service footer component
=> feat: added EEA state questions

controllers/sprint-90/eligibility/nationality-other.js, controllers/sprint-90/eligibility/nationality-swiss-eea.js, controllers/sprint-90/eligibility/residence-country.js, controllers/sprint-90/index.js, routes/sprint-90.js, utils/constants.js, views/sprint-90/nationality-swiss-eea.njk
- added /nationality-swiss-eea
- updated conditional routing
=> feat: added swiss or eea state conditional question

controllers/sprint-90/index.js, controllers/sprint-90/payability/care-home-funding-trusts.js, controllers/sprint-90/payability/care-home-funding-who.js, routes/sprint-90.js, utils/constants.js, views/sprint-90/care-home-funding-trusts.njk
- added care-home-funding-trusts to capture NI funding
- updated routing
=> feat: added health and social care trusts for ni

views/sprint-90/accessibility-statement.njk
Removed 'What we're doing to improve accessibility' section as changes have been made to the change links. Also updated 'last reviewed' date to today's date.
=> refactor: updated accessibility statement

views/sprint-92/aids-adaptations-reason.njk, views/sprint-92/bed-day-why.njk, views/sprint-92/bed-day.njk, views/sprint-92/bed-position-night-frequency.njk, views/sprint-92/bed-position-night.njk, views/sprint-92/communication-day.njk, views/sprint-92/dress-day-why.njk, views/sprint-92/dress-day.njk, views/sprint-92/eat-drink-day-why.njk, views/sprint-92/eat-drink-day.njk, views/sprint-92/falling-or-stumbling-why.njk, views/sprint-92/medication-treatment-day-why.njk, views/sprint-92/medication-treatment-day.njk, views/sprint-92/medication-treatment-night-frequency.njk, views/sprint-92/medication-treatment-night-why.njk, views/sprint-92/medication-treatment-night.njk, views/sprint-92/moving-indoors-day.njk, views/sprint-92/moving-indoors-stairs.njk, views/sprint-92/moving-indoors-why.njk, views/sprint-92/safe-day-why.njk, views/sprint-92/social-activities-day.njk, views/sprint-92/toilet-day-why.njk, views/sprint-92/toilet-day.njk, views/sprint-92/toilet-night-frequency.njk, views/sprint-92/toilet-night-why.njk, views/sprint-92/toilet-night.njk, views/sprint-92/turning-over-night-frequency.njk, views/sprint-92/wash-day-why.njk, views/sprint-92/wash-day.njk
=> feat(4070): more character counts

views/sprint-92/best-describe.njk
updated two bullet points on NI version of /best-describes as prototype did not match main
=> refactor: update best describes

views/index.njk
added 'Updated Accessibility Statement' to index page as this was missing
=> refactor: updated index page

views/index.njk
updated index page to move accessibility changes to sprint 91
=> refactor:changes to index

controllers/sprint-94/eligibility/birth-date.js, controllers/sprint-94/index.js, controllers/sprint-94/visiting-service/effective-date.js, routes/sprint-94.js, utils/constants.js, views/index.njk, views/sprint-94/effective-date.njk, views/sprint-94/macros/check-answers-details-section.njk
- added /effective-date
- updated routing so VO's don't see who-is-applying
=> feat: visiting service effective date

controllers/sprint-94/claim-type/claim-type-change-in-circumstances.js, controllers/sprint-94/claim-type/claim-type-renewal.js, controllers/sprint-94/claim-type/claim-type.js, controllers/sprint-94/eligibility/adp-ineligible.js, controllers/sprint-94/eligibility/dla-ineligible.js, controllers/sprint-94/eligibility/other-benefits.js, controllers/sprint-94/eligibility/pip-ineligible.js, controllers/sprint-94/index.js, routes/sprint-94.js, utils/constants.js, views/index.njk, views/sprint-94/adp-ineligible.njk, views/sprint-94/birth-date-ineligible.njk, views/sprint-94/claim-type-change-in-circumstances.njk, views/sprint-94/claim-type-renewal.njk, views/sprint-94/claim-type.njk, views/sprint-94/country-outside-uk-duration-ineligible.njk, views/sprint-94/dla-ineligible.njk, views/sprint-94/macros/check-answers-details-section.njk, views/sprint-94/pip-ineligible.njk, views/sprint-94/residence-country-ineligible.njk
Added /effective-date for Visiting Officers
Updated /birth-date-ineligible
Updated routing on /other-benefits
Added /pip-ineligible
Added /dla-ineligible
Added /adp-ineligible
Updated /attendance-allowance-ineligible
Updated /residence-country-ineligible
Updated /country-outside-uk-duration-ineligible
New concept /claim-type
=> feat: aag-3475 ineligible pages review

controllers/sprint-95/eligibility/who-is-applying.js, controllers/sprint-95/index.js, controllers/sprint-95/start/before-you-start-ineligible.js, controllers/sprint-95/start/before-you-start.js, routes/sprint-95.js, utils/constants.js, views/index.njk, views/sprint-95/before-you-start-ineligible.njk, views/sprint-95/before-you-start.njk
- updated /before-you-start
- updated back routing on /who-is-applying
- added /before-you-start-ineligible
=> feat: updates to before-you-start for a/b test

views/sprint-95/special-rules-form-guidance.njk
updated guidance page for SREL upload to include that SR1 has two pages
=> refactor: update guidance

controllers/sprint-95/claim-type/claim-type.js, controllers/sprint-95/eligibility/other-benefits.js, views/index.njk, views/sprint-95/claiming-end-of-life.njk, views/sprint-95/how-to-claim.njk
- /claim-type is now the start of the journey
- Routing now goes /claim-type --> /before-you-start --> /who-is-applying
- Revert other-benefits routing for PIP, DLA and ADP back to /other-benefits-ineligible
=> feat: updated routing for start of journey

views/sprint-97/consent.njk
added locale NI content variation
=> refactor: aag-4311 NI consent

controllers/sprint-98/eligibility/country-outside-uk-duration.js, controllers/sprint-98/eligibility/previous-residence-scotland.js, controllers/sprint-98/eligibility/residence-country.js, controllers/sprint-98/identity/full-name.js, controllers/sprint-98/identity/home-address-manual.js, controllers/sprint-98/identity/home-address-postcode.js, controllers/sprint-98/identity/home-address-select.js, controllers/sprint-98/payability/care-home-hospital.js, views/sprint-98/home-address-postcode.njk, views/sprint-98/previous-residence-scotland.njk
- moved postcode select after residence-country for scotland
- updated routing
=> feat(aag-4317): updated routing for scottish devolution postcodes

views/sprint-99/eligibility.njk, views/sprint-99/overview.njk
updated gov eligibility pages to match changes made by GDS
=> refactor: update gov eligibility

controllers/sprint-100/consent/healthcare-professional-add.js, controllers/sprint-100/consent/healthcare-professional-details.js, controllers/sprint-100/consent/healthcare-professional-options.js, controllers/sprint-100/index.js, routes/sprint-100.js, utils/constants.js, views/index.njk, views/sprint-100/check-answers-details.njk, views/sprint-100/healthcare-professional-add.njk, views/sprint-100/healthcare-professional-details.njk, views/sprint-100/healthcare-professional-options.njk, views/sprint-100/macros/check-answers-details-section.njk
- added healthcare-professional-add
- added healthcare-professional-options
- added healthcare-professional-details
- updated routing
- updated check-answers-details
=> feat: add another healthcare professional

controllers/sprint-103/contact-details/add-contact-details.js, controllers/sprint-103/contact-details/telephone-number.js, controllers/sprint-103/eligibility/best-describe.js, controllers/sprint-103/eligibility/birth-date.js, controllers/sprint-103/identity/home-address-international.js, controllers/sprint-103/identity/home-address-manual.js, controllers/sprint-103/identity/home-address-select.js, controllers/sprint-103/official-capacity/representative-name.js, controllers/sprint-103/official-capacity/representative-telephone-number.js, controllers/sprint-103/payability/care-home-hospital.js, controllers/sprint-103/start/helping-someone-intro.js, views/index.njk, views/sprint-102/representative-birth-date.njk, views/sprint-103/check-answers-details.njk, views/sprint-103/helping-someone-intro.njk, views/sprint-103/macros/check-answers-contact-details-section.njk, views/sprint-103/macros/check-answers-details-section.njk, views/sprint-103/representative-birth-date.njk
- added appointee test 2
- reroute journey for test scenario
=> feat(aag-4239): add appointee test 2

controllers/sprint-103/contact-details/telephone-number.js, controllers/sprint-103/identity/home-address-postcode.js, controllers/sprint-103/identity/national-insurance.js, controllers/sprint-103/official-capacity/representative-address-postcode.js, controllers/sprint-103/official-capacity/representative-national-insurance.js, controllers/sprint-103/official-capacity/representative-telephone-number.js, views/sprint-103/helping-someone-intro.njk, views/sprint-103/macros/check-answers-details-section.njk
- removed validation for postcode, NINO and telephone for testing purposes
- updated check-answers-details
=> feat: update appointee validation and check answers

controllers/sprint-105/consent/consent.js, controllers/sprint-105/evidence/supporting-documents-email-address.js, controllers/sprint-105/evidence/supporting-documents-email-link.js, controllers/sprint-105/evidence/supporting-documents-guidance.js, controllers/sprint-105/evidence/supporting-documents-intro.js, controllers/sprint-105/evidence/supporting-documents-options.js, controllers/sprint-105/evidence/supporting-documents-post.js, controllers/sprint-105/evidence/supporting-documents-upload-later.js, controllers/sprint-105/evidence/supporting-documents-upload.js, controllers/sprint-105/index.js, routes/sprint-105.js, utils/constants.js, views/index.njk, views/sprint-105/done.njk, views/sprint-105/supporting-documents-email-address.njk, views/sprint-105/supporting-documents-email-link.njk, views/sprint-105/supporting-documents-guidance.njk, views/sprint-105/supporting-documents-intro.njk, views/sprint-105/supporting-documents-options.njk, views/sprint-105/supporting-documents-post.njk, views/sprint-105/supporting-documents-upload-later.njk, views/sprint-105/supporting-documents-upload.njk
- added new designs
- updated routing
=> feat(aag-4562): medical evidence test

controllers/sprint-109/eligibility/other-benefits.js, views/evidence-test-5/pip-ineligible.njk, views/index.njk, views/sprint-109/adp-ineligible.njk, views/sprint-109/attendance-allowance-ineligible.njk, views/sprint-109/birth-date-ineligible.njk, views/sprint-109/dla-ineligible.njk, views/sprint-109/no-difficulties-ineligible.njk, views/sprint-109/pip-ineligible.njk, views/sprint-109/residence-country-ineligible.njk
- Updated /birth-date-ineligible
- Added /pip-ineligible
- Added /adp-ineligible
- Added /dla-ineligible
- Updated /attendance-allowance-ineligible
- Updated /residence-country-ineligible
- Updated /country-outside-uk-duration-ineligible
- Added /no-difficulties-ineligible
=> feat: ineligible page iterations
